CREATE TABLE ANSATT
(
  ID   NUMBER GENERATED ALWAYS AS IDENTITY,
  NAVN VARCHAR2(255),
  CONSTRAINT "PK_ANSATT" PRIMARY KEY ("ID")
);


CREATE TABLE KUNDE
(
  ID   NUMBER GENERATED ALWAYS AS IDENTITY,
  NAVN VARCHAR2(255),
  CONSTRAINT "PK_KUNDE" PRIMARY KEY ("ID")
);

CREATE TABLE PRODUKT
(
  ID          NUMBER GENERATED ALWAYS AS IDENTITY,
  BESKRIVELSE VARCHAR2(255),
  PRIS        NUMBER,
  CONSTRAINT "PK_PRODUKT" PRIMARY KEY ("ID")
);


CREATE TABLE SALG
(
  ID         NUMBER GENERATED ALWAYS AS IDENTITY,
  ANTALL     NUMBER,
  TOTAL_PRIS NUMBER,
  SELGER     NUMBER,
  KUNDE      NUMBER,
  PRODUKT    NUMBER,
  CONSTRAINT "PK_PRODUKT" PRIMARY KEY ("ID")
);

CREATE INDEX IX_SALG_SELGER ON SALG (SELGER);
CREATE INDEX IX_SALG_KUNDE ON SALG (KUNDE);
CREATE INDEX IX_SALG_PRODUKT ON SALG (PRODUKT);

