CREATE TABLE SELGER
(
  ID   NUMBER GENERATED ALWAYS AS IDENTITY,
  NAVN VARCHAR2(255),
  CONSTRAINT "PK_ANSATT" PRIMARY KEY ("ID")
);


CREATE TABLE KUNDE
(
  ID   NUMBER GENERATED ALWAYS AS IDENTITY,
  NAVN VARCHAR2(255),
  CONSTRAINT "PK_KUNDE" PRIMARY KEY ("ID")
);

CREATE TABLE PRODUKT
(
  ID          NUMBER GENERATED ALWAYS AS IDENTITY,
  BESKRIVELSE VARCHAR2(255),
  PRIS        NUMBER,
  CONSTRAINT "PK_PRODUKT" PRIMARY KEY ("ID")
);


CREATE TABLE SALG
(
  ID         NUMBER GENERATED ALWAYS AS IDENTITY,
  ANTALL     NUMBER,
  TOTAL_PRIS NUMBER,
  SELGER     NUMBER,
  KUNDE      NUMBER,
  PRODUKT    NUMBER,
  CONSTRAINT "PK_SALG" PRIMARY KEY ("ID")
);

CREATE TABLE SALG_HENDELSE
(
  ID         NUMBER GENERATED ALWAYS AS IDENTITY,
  SALG_ID    NUMBER,
  HENDELSE    VARCHAR2(40),
  OPPRETTET  TIMESTAMP(6),
  CONSTRAINT "PK_SALG_HENDELSE" PRIMARY KEY ("ID")
);

CREATE INDEX IX_SALG_HENDELSE_SALG ON SALG_HENDELSE (SALG_ID);
CREATE INDEX IX_SALG_SELGER ON SALG (SELGER);
CREATE INDEX IX_SALG_KUNDE ON SALG (KUNDE);
CREATE INDEX IX_SALG_PRODUKT ON SALG (PRODUKT);

